### ISSUE TITLE
Installation error............

### ISSUE THREAD

**Issue by princessfrombabylon99** [TridotsTech/Go1-Commerce#3]
It throws error , it is not working on live server. It conflicts with erpnext.  Doesn't seems to be of any use. Somehow, I managed to restore my instance. Kindly look into this.

**Comment by clayrisser** [comment]
Can you confirm if it's the same error as  #4?

**Comment by princessfrombabylon99** [comment]
@clayrisser Yes

**Comment by mumbaigirl** [comment]
+1

**Comment by thatphythonguy** [comment]
+1

**Comment by thatphythonguy** [comment]
+1 , any workaround? @clayrisser

**Comment by clayrisser** [comment]
The only solution would be running both platforms separately and using something like Keycloak to SSO into both platforms.

https://www.keycloak.org
